In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np


In [3]:
import numpy as np
a=np.array([2,4,6])
b=np.array([3,1,2])
print(a+b)

[5 5 8]


In [4]:
#array creation function
np.arange(3,100,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [5]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [6]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [8]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.random.rand(1,5)

array([[0.32945799, 0.74810356, 0.43465788, 0.25300572, 0.32597194]])

In [10]:
[np.random.randint(2,7) for _ in range (6)]

[6, 5, 3, 4, 5, 4]

In [11]:
np.random.randint(2,6,size=(2,3))

array([[5, 3, 4],
       [2, 4, 4]], dtype=int32)

In [12]:
#aray properties
b=np.array([[1,2,3],[4,5,6]])
b.ndim
b.shape
b.size
b.dtype


dtype('int64')

In [13]:
#array reshaping
b.reshape((3,2))
print(b)
b.reshape((-1,1))

[[1 2 3]
 [4 5 6]]


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [14]:
c=np.array([[2,3],[4,5]])
c1=c.flatten()
c[0]=8
print(c)
print(c1)


[[8 8]
 [4 5]]
[2 3 4 5]


In [15]:
c=np.array([[2,3],[4,5]])
c1=c.ravel()
c1[0]=8
print(c)
c.ravel()

[[8 3]
 [4 5]]


array([8, 3, 4, 5])

In [16]:
d=np.array([[[1,4,6,7],[5,9,56,3]],[[2,34,78,1],[8,4,32,6]]])
d[1][1][0]

np.int64(8)

In [17]:
d[:1]

array([[[ 1,  4,  6,  7],
        [ 5,  9, 56,  3]]])

In [18]:
# reverse array
import numpy as np
arr=np.array([1,3,5,7,9])
r_arr=arr[::-1]
print(r_arr)

[9 7 5 3 1]


In [19]:
#indexing
f=np.array([[[2,4,6,8],[1,3,5,7]],[[9,11,13,15],[10,12,14,16]]])
f[1][0][2]


np.int64(13)

In [20]:
#boolean index filtering
f=np.array([[[2,4,6,8],[1,3,5,7]],[[9,11,13,15],[10,12,14,16]]])
f[f>9]

array([11, 13, 15, 10, 12, 14, 16])

In [21]:
ab=np.array([[1,2,3,4],[5,6,7,8]])
ab[:,[0,2]]

array([[1, 3],
       [5, 7]])

In [22]:
np.random.randn(2,8)

array([[ 0.90122569, -0.82117867, -0.42385016, -1.18693392, -0.69237436,
        -0.65698423,  0.12264013,  0.2960192 ],
       [-1.70631835, -0.11465033, -0.32001234, -1.0668307 , -0.43193013,
         1.42378623, -0.13246886, -1.05938005]])

In [23]:
A=np.arange(15,24).reshape(3,3)
B=np.arange(20,29).reshape(3,3)
print("A: ",A)
print("B: ",B)




A:  [[15 16 17]
 [18 19 20]
 [21 22 23]]
B:  [[20 21 22]
 [23 24 25]
 [26 27 28]]


In [25]:
import numpy as np
sa=np.array([[0.43934631, -0.89454494, -0.78472377],
             [-0.41975758, -0.26508408, -0.66358511]])
sa

array([[ 0.43934631, -0.89454494, -0.78472377],
       [-0.41975758, -0.26508408, -0.66358511]])

In [26]:
# statistics
np.mean(sa)

np.float64(-0.43139152833333333)

In [27]:
np.std(sa)

np.float64(0.4433295452853014)

In [28]:
np.var(sa)

np.float64(0.1965410857228721)

In [29]:
np.median(sa)

np.float64(-0.541671345)

In [30]:
np.min(sa)

np.float64(-0.89454494)

In [31]:
np.max(sa)

np.float64(0.43934631)

In [36]:
np.percentile(10,100)

np.float64(10.0)

In [37]:
#aggregation
print(d)
np.sum(d,axis=0) # column-wise

[[[ 1  4  6  7]
  [ 5  9 56  3]]

 [[ 2 34 78  1]
  [ 8  4 32  6]]]


array([[ 3, 38, 84,  8],
       [13, 13, 88,  9]])

In [38]:
np.sum(d,axis=1) #row=wise

array([[  6,  13,  62,  10],
       [ 10,  38, 110,   7]])

In [39]:
np.random.seed(42)
np.random.normal(3,1)

3.496714153011233

In [40]:
#sorting
np.argsort(d)

array([[[0, 1, 2, 3],
        [3, 0, 1, 2]],

       [[3, 0, 1, 2],
        [1, 3, 0, 2]]])

In [41]:
np.sort(d)

array([[[ 1,  4,  6,  7],
        [ 3,  5,  9, 56]],

       [[ 1,  2, 34, 78],
        [ 4,  6,  8, 32]]])

In [42]:
np.vstack(d)

array([[ 1,  4,  6,  7],
       [ 5,  9, 56,  3],
       [ 2, 34, 78,  1],
       [ 8,  4, 32,  6]])

In [43]:
np.hstack(d)

array([[ 1,  4,  6,  7,  2, 34, 78,  1],
       [ 5,  9, 56,  3,  8,  4, 32,  6]])

In [44]:
#broadcasting
a=np.array([[1,2,3],[4,5,6]]) #shape(2,3)
b=np.array([1,2,3]) #shape (3, )
r=a+b
r

array([[2, 4, 6],
       [5, 7, 9]])